theme = "onedark"

[editor]
auto-completion = true
path-completion = true
line-number = "relative"
mouse = true
cursorline = true
cursorcolumn = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
